# Usar a imagem oficial do Node.js
FROM node:18

# Criar e definir o diretório de trabalho
WORKDIR /app

# Copiar arquivos de dependências
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar todo o código-fonte para o container
COPY . .

# Expor a porta padrão do servidor de desenvolvimento
EXPOSE 5173

# Rodar o servidor de desenvolvimento do Vue
CMD ["npm", "run", "dev"]